In [2]:
import numpy as np


In [6]:
# Student Marks Analysis 
# Here is numpy array containing marks of 40 students in eight subjects.
# rows represent 40 students and column represent 8 subjects
np.random.seed(42)
student_marks = np.random.randint(50,100, size = (40,8))


In [9]:
student_marks

array([[88, 78, 64, 92, 57, 70, 88, 68],
       [72, 60, 60, 73, 85, 89, 73, 52],
       [71, 51, 73, 93, 79, 87, 51, 70],
       [82, 61, 71, 93, 74, 98, 76, 91],
       [77, 65, 64, 96, 93, 52, 86, 56],
       [70, 58, 88, 67, 53, 74, 63, 99],
       [58, 75, 51, 69, 77, 96, 56, 93],
       [57, 96, 84, 63, 66, 85, 99, 89],
       [53, 51, 55, 91, 53, 78, 67, 75],
       [93, 83, 59, 85, 63, 80, 97, 64],
       [57, 63, 72, 89, 70, 65, 94, 67],
       [96, 73, 75, 74, 94, 90, 78, 64],
       [94, 50, 74, 56, 58, 73, 50, 93],
       [57, 73, 60, 66, 57, 84, 84, 82],
       [54, 91, 88, 90, 77, 56, 58, 57],
       [61, 83, 82, 97, 72, 73, 86, 84],
       [93, 89, 71, 76, 84, 50, 84, 86],
       [96, 63, 52, 50, 54, 75, 63, 88],
       [76, 58, 64, 64, 75, 91, 62, 81],
       [88, 98, 81, 53, 79, 86, 72, 88],
       [94, 64, 92, 78, 85, 62, 81, 56],
       [71, 77, 51, 91, 94, 55, 77, 77],
       [93, 93, 69, 79, 60, 77, 74, 88],
       [82, 50, 76, 62, 90, 52, 88, 55],
       [57, 76, 

In [11]:
# Checking the dataset 
print("Shape: ", student_marks.shape)
print("Size: ",student_marks.size)
print("Dimensions:", student_marks.ndim)

Shape:  (40, 8)
Size:  320
Dimensions: 2


In [17]:
# Overall Statistics
print("Mean = ", np.mean(student_marks))
print("Median = ", np.median(student_marks))
print("Standard Deviation = ", np.std(student_marks))
print("Minimum = ", np.min(student_marks))
print("Maximum = ", np.max(student_marks))
print("Total Marks = ", np.sum(student_marks))

Mean =  74.23125
Median =  75.0
Standard Deviation =  14.414065125338515
Minimum =  50
Maximum =  99
Total Marks =  23754


In [19]:
# Average marks of each student
avg_marks_student = np.mean(student_marks, axis = 1)
avg_marks_student

array([75.625, 70.5  , 71.875, 80.75 , 73.625, 71.5  , 71.875, 79.875,
       65.375, 78.   , 72.125, 80.5  , 68.5  , 70.375, 71.375, 79.75 ,
       79.125, 67.625, 71.375, 80.625, 76.5  , 74.125, 79.125, 69.375,
       77.   , 80.75 , 79.625, 68.75 , 69.625, 68.625, 70.   , 67.25 ,
       80.25 , 73.875, 77.125, 72.125, 73.75 , 77.25 , 81.625, 72.125])

In [21]:
# Average marks in each subject
avg_marks_subject = np.mean(student_marks, axis = 0)
print(avg_marks_subject)

[72.825 70.45  72.775 75.5   75.275 76.7   75.725 74.6  ]


In [25]:
# Find the highest-scoring student
best_student_index = np.argmax(np.max(student_marks, axis = 1))
print("Best Student = ", best_student_index + 1)
print("Highest Score made by best student = ", np.max(student_marks[best_student_index]))

Best Student =  6
Highest Score made by best student =  99


In [29]:
# Find the lowest-scoring student
worst_stu_index = np.argmin(np.min(student_marks, axis = 1))
print("Worst Student= ", worst_stu_index + 1)
print("Lowest score made by the worst student = ", np.min(student_marks[worst_stu_index]))

Worst Student=  13
Lowest score made by the worst student =  50


In [36]:
# Student who score above 95 in any subject
mask = np.any(student_marks > 95, axis = 1)
above_95_scorer = student_marks[mask]
print(above_95_scorer)

[[82 61 71 93 74 98 76 91]
 [77 65 64 96 93 52 86 56]
 [70 58 88 67 53 74 63 99]
 [58 75 51 69 77 96 56 93]
 [57 96 84 63 66 85 99 89]
 [93 83 59 85 63 80 97 64]
 [96 73 75 74 94 90 78 64]
 [61 83 82 97 72 73 86 84]
 [96 63 52 50 54 75 63 88]
 [88 98 81 53 79 86 72 88]
 [64 81 81 73 90 98 98 61]
 [88 51 52 98 86 98 66 98]
 [60 97 65 82 58 55 65 78]
 [50 60 77 74 99 72 80 79]
 [91 84 56 65 75 97 98 51]
 [50 97 61 54 86 81 58 90]
 [84 68 97 65 52 69 73 82]
 [73 60 98 57 85 87 89 69]
 [84 97 74 84 74 78 67 95]]


In [39]:
# Top 10% scores
threshold = np.percentile(student_marks, 90)
print("Top 10% threshold:", threshold)
mask = student_marks >= threshold
print("10% score = ",student_marks[mask])

Top 10% threshold: 93.0
10% score =  [93 93 98 96 93 99 96 93 96 99 93 97 94 96 94 94 93 97 93 96 98 94 94 93
 93 93 98 98 98 98 98 93 97 99 97 98 97 97 98 97 95]


In [40]:
avg_marks_student

array([75.625, 70.5  , 71.875, 80.75 , 73.625, 71.5  , 71.875, 79.875,
       65.375, 78.   , 72.125, 80.5  , 68.5  , 70.375, 71.375, 79.75 ,
       79.125, 67.625, 71.375, 80.625, 76.5  , 74.125, 79.125, 69.375,
       77.   , 80.75 , 79.625, 68.75 , 69.625, 68.625, 70.   , 67.25 ,
       80.25 , 73.875, 77.125, 72.125, 73.75 , 77.25 , 81.625, 72.125])

In [41]:
# Give grades
grades = np.where(
    avg_marks_student >= 90, "A+",
    np.where(
        avg_marks_student >= 80, "A",
        np.where(
            avg_marks_student >= 70,"B",
            np.where(
                avg_marks_student >=60, "C", "F"
            )
        )
    )
)
print(grades)

['B' 'B' 'B' 'A' 'B' 'B' 'B' 'B' 'C' 'B' 'B' 'A' 'C' 'B' 'B' 'B' 'B' 'C'
 'B' 'A' 'B' 'B' 'B' 'C' 'B' 'A' 'B' 'C' 'C' 'C' 'B' 'C' 'A' 'B' 'B' 'B'
 'B' 'B' 'A' 'B']
